import './globals.css'

import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import { Footer } from './_components/footer'
import { Toaster } from './_components/ui/sonner'
import AuthProvider from './_providers/auth'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`dark ${nunito.className}`}>
        <AuthProvider>
          <div className="flex-1">{children}</div>
          <Toaster />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
